SET SERVEROUTPUT ON

CREATE OR REPLACE TRIGGER check_salary
BEFORE INSERT OR UPDATE ON emp
FOR EACH ROW
BEGIN
    IF :NEW.salary > 50000 THEN
        RAISE_APPLICATION_ERROR(-20002, 'Salary cannot exceed 50000');
    END IF;
END;
/